
name: Deploy Shopify Hydrogen Application
on:
  push:
    branches:
      - main # can be changed to any branch you prefer
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x
    - name: Build
      run: npm install && npm run build
